package booking.price;

public enum Category {
	SINGLE, DOUBLE, TRIPLE, QUAD, HOLYWOOD_TWIN, QUEEN_ROOM, TWIN_ROOM, KING_ROOM, DOUBLE_HOTEL_ROOM, STUDIO_HOTEL_ROOM,
	ACCESSIBLE_ROOM, SUITE, MINI_SUITE, APARTMENT_STYLE_HOTELS, STANDARD_ROOM_HOTEL, CONNECTING_ROOM, PRESIDENTAL_SUITE,
	DELUXE_ROOM, SUPER_DELUXE, JOINT_ROOM, CABANA, VILLA, PENTHOUSE_SUITE, FLOORED_ROOM, SMOKING_ROOM

}
// https://viatravelers.com/types-of-hotel-rooms/
